// packages/craftily-vue/src/components/Button/Button.vue
<template>
  <craftily-button
    :variant="variant"
    :size="size"
    :disabled="disabled"
    :icon-position="iconPosition"
    :label="label"
    :class="className"
    v-bind="attrs"
    @click="handleClick"
  >
    <!-- Pass Button.vue's 'icon' slot to craftily-button's 'icon' slot -->
    <slot name="icon" slot="icon"></slot>

    <!-- Pass Button.vue's default slot to craftily-button's 'label' slot -->
    <!-- If this slot is empty, craftily-button will use its 'label' prop as fallback -->
    <slot slot="label"></slot>
  </craftily-button>
</template>

<script setup lang="ts">
import { onMounted, useAttrs } from 'vue';
import '@craftily/ui/button';

defineOptions({
  name: 'Button', // Added for Devtools
  inheritAttrs: false,
});

export interface ButtonProps {
  variant?:
    | 'primary'
    | 'secondary'
    | 'accent'
    | 'ghost'
    | 'outline'
    | 'success'
    | 'error'
    | 'warning'
    | 'info';
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl' | '3xl' | '4xl';
  disabled?: boolean;
  iconPosition?: 'left' | 'right';
  label?: string; // This prop provides fallback label text
  className?: string; // CSS class name
}

// No need for `interface Props extends ButtonProps {}`
// Directly use ButtonProps with defineProps
const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
  iconPosition: 'left',
  label: undefined,
  className: undefined,
});

const emit = defineEmits(['click']);

// Access attributes not defined as props
const attrs = useAttrs();

const handleClick = (event: Event) => {
  // The craftily-button emits a CustomEvent with detail: { originalEvent: Event }
  if (event instanceof CustomEvent && event.detail) {
    emit('click', event);
  }
};

onMounted(() => {
  if (!customElements.get('craftily-button')) {
    console.warn('craftily-button web component is not defined');
  }
});
</script>

// packages/craftily-react/src/components/Button/index.tsx
import React, { forwardRef, useCallback, useEffect } from 'react';
import '@craftily/ui/button';

export interface ButtonProps extends Omit<React.HTMLAttributes<HTMLElement>, 'label' | 'onClick'> {
  variant?: 'default' | 'primary' | 'secondary' | 'accent' | 'ghost' | 'link';
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  loading?: boolean;
  icon?: React.ReactNode;
  iconPosition?: 'left' | 'right';
  label?: React.ReactNode;
  children?: React.ReactNode;
  onClick?: (event: CustomEvent<{ originalEvent: Event }>) => void;
}

export const Button = forwardRef<HTMLElement, ButtonProps>((props, ref) => {
  const { variant, size, disabled, iconPosition, icon, label, className, children, onClick, ...rest } =
    props;

  const handleClick = useCallback(
    (e: Event) => {
      // The craftily-button emits a CustomEvent with detail: { originalEvent: Event }
      if (onClick && e instanceof CustomEvent) {
        onClick(e);
      }
    },
    [onClick]
  );

  useEffect(() => {
    // Using a local variable to store the element reference
    let element: HTMLElement | null = null;
    
    // Handle both RefObject and callback ref types
    if (ref) {
      if (typeof ref === 'function') {
        // We can't access the DOM element directly from a callback ref
        // The element will be handled through the ref prop on the component
      } else if (ref.current) {
        element = ref.current;
      }
    }
    
    if (!element) return;

    element.addEventListener('click', handleClick);
    return () => element?.removeEventListener('click', handleClick);
  }, [handleClick, ref]);

  return React.createElement(
    'craftily-button',
    {
      ref,
      variant,
      size,
      disabled,
      'icon-position': iconPosition,
      class: className,
      ...rest,
    },
    [
      icon && React.createElement('span', { key: 'icon', slot: 'icon' }, icon),
      label && React.createElement('span', { key: 'label', slot: 'label' }, label),
      children,
    ]
  );
});

Button.displayName = 'Button';
export default Button;
