// packages/craftily-react/src/components/Switch/index.tsx
import React, { useRef, useEffect, useCallback } from 'react';
import '@craftily/ui/switch';

export interface SwitchProps {
  checked?: boolean;
  disabled?: boolean;
  name?: string;
  onChange?: (checked: boolean) => void;
  className?: string;
}

export const Switch = React.forwardRef<HTMLElement, SwitchProps>((props, ref) => {
  const { checked, disabled, name, onChange, className } = props;
  const elementRef = useRef<HTMLElement | null>(null);

  const handleChange = useCallback(
    (e: Event) => {
      // The craftily-switch emits a CustomEvent with detail: { checked: boolean }
      if (e instanceof CustomEvent && e.detail && typeof e.detail.checked === 'boolean') {
        onChange?.(e.detail.checked);
      }
    },
    [onChange]
  );

  useEffect(() => {
    const element = elementRef.current;
    if (!element) return;

    element.addEventListener('change', handleChange);
    return () => element.removeEventListener('change', handleChange);
  }, [handleChange]);

  return React.createElement(
    'craftily-switch',
    {
      ref,
      checked,
      disabled,
      name,
      class: className,
      onChange: handleChange,
    },
    null
  );
});

// packages/craftily-vue/src/components/Switch/Switch.vue
<template>
  <craftily-switch
    :checked="modelValue"
    :disabled="disabled"
    :name="name"
    :class="className"
    v-bind="attrs"
    @change="handleChange"
  ></craftily-switch>
</template>

<script setup lang="ts">
import { useAttrs } from 'vue';
import '@craftily/ui/switch';

defineOptions({
  name: 'CraftilySwitch',
  inheritAttrs: false,
});

export interface SwitchProps {
  modelValue?: boolean;
  disabled?: boolean;
  name?: string;
  className?: string;
}

const props = withDefaults(defineProps<SwitchProps>(), {
  modelValue: false,
  disabled: false,
  name: '',
  className: '',
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void;
}>();

// Access attributes not defined as props
const attrs = useAttrs();

const handleChange = (event: Event) => {
  // The craftily-switch emits a CustomEvent with detail: { checked: boolean }
  if (event instanceof CustomEvent && event.detail && typeof event.detail.checked === 'boolean') {
    emit('update:modelValue', event.detail.checked);
  }
};
</script>
