// packages/craftily-vue/src/components/ImageEditor.vue
<!-- packages/craftily-vue/src/components/ImageEditor.vue -->
<template>
  <div>
    <craftily-image-editor
      :controls="controls"
      :showDownload="false"
      showUpload="true"
      @image-edited="handleImageEdited"
      ref="editorRef"
    ></craftily-image-editor>
  </div>
</template>

<script setup lang="ts">
import { ControlProps, ImageEditedEventDetail } from '@craftily/image';
import '@craftily/image/editor';
import { ref } from 'vue';

const emit = defineEmits<{
  (e: 'imageEdited', details: string): void;
}>();

defineProps<{
  controls?: ControlProps;
}>();

const editorRef = ref<HTMLElement>();

const handleImageEdited = (event: CustomEvent<ImageEditedEventDetail>) => {
  // Emit the edited image
  emit('imageEdited', event.detail.toDataURL());
};
</script>

// packages/craftily-react/src/components/ImageEditor/index.tsx
import React, { useEffect, useRef } from 'react';
import '@craftily/image/editor';
import { ControlProps } from '@craftily/image';

// Define props interface for the component
interface ImageEditorProps {
  onImageEdit?: (editedImage: string) => void;
  initialImage?: string;
  controls?: ControlProps;
  showUpload?: boolean;
  showDownload?: boolean;
}

export const ImageEditor: React.FC<ImageEditorProps> = ({
  onImageEdit,
  initialImage,
  controls,
  showUpload,
  showDownload,
}) => {
  const editorRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const editorElement = editorRef.current as HTMLElement;

    if (editorElement) {
      // Add event listener for image editing
      const handleImageEdit = (event: Event) => {
        const customEvent = event as CustomEvent<string>;
        onImageEdit?.(customEvent.detail);
      };

      editorElement.addEventListener('image-edited', handleImageEdit);

      // Cleanup event listener
      return () => {
        editorElement.removeEventListener('image-edited', handleImageEdit);
      };
    }
  }, [initialImage, onImageEdit]);

  return React.createElement('craftily-image-editor', {
    ref: editorRef,
    src: initialImage || '',
    controls,
    showUpload,
    showDownload,
  });
};
ImageEditor.displayName = 'ImageEditor';
export default ImageEditor;
